package main

import (
	"crypto/ecdsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"time"

	"github.com/hyperledger/fabric-contract-api-go/contractapi"
)

// SmartContract provides functions for managing a FileRecord
type SmartContract struct {
	contractapi.Contract
}

// FileRecord represents a single file integrity event on the blockchain.
// Every security-critical field is explicitly tracked here.
type FileRecord struct {
	TxID                string `json:"tx_id"`                   // Fabric transaction ID
	FilePath            string `json:"file_path"`               // Canonical path on endpoint
	Blake3Hash          string `json:"blake3_hash"`             // High-throughput integrity hash
	Sha256Hash          string `json:"sha256_hash"`             // FIPS-compliant hash
	IpfsCID             string `json:"ipfs_cid"`                // Pointer to off-chain encrypted content
	DekKeyRef           string `json:"dek_key_ref"`             // HSM reference to DEK (NEVER the raw key)
	AgentID             string `json:"agent_id"`                // Registered edge agent identity
	TimestampNano       int64  `json:"timestamp_nano"`          // Event time from endpoint
	HSMSignature        string `json:"hsm_signature"`           // ECDSA-P384 signature over payload fields
	AttestationHash     string `json:"attestation_token_hash"`  // Binds event to agent binary integrity state
	ComplianceStateRoot string `json:"compliance_state_root"`   // Merkle root used for ZKP verification
	ComplianceStatus    string `json:"compliance_status"`       // COMPLIANT, NON_COMPLIANT, UNDER_INVESTIGATION
}

// SuspiciousFlag is appended by the AI Layer if an anomaly is detected
type SuspiciousFlag struct {
	OriginalTxID string  `json:"original_tx_id"`
	AnomalyScore float64 `json:"anomaly_score"`
	Explanation  string  `json:"explanation"`
	Timestamp    int64   `json:"timestamp"`
}

// InitLedger initializes the ledger (empty for now)
func (s *SmartContract) InitLedger(ctx contractapi.TransactionContextInterface) error {
	return nil
}

// LogFileChange records a new file change event to the ledger.
// Access Control: Only registered agent identities may invoke this function.
func (s *SmartContract) LogFileChange(
	ctx contractapi.TransactionContextInterface,
	filePath, blake3Hash, sha256Hash, ipfsCID, dekKeyRef, agentID string,
	timestampNano int64, hsmSignature, attestationHash string, zkpProof string) error {

	// -------------------------------------------------------------------------
	// 1. ACCESS CONTROL: Validate caller identity
	// -------------------------------------------------------------------------
	clientID, err := ctx.GetClientIdentity().GetID()
	if err != nil {
		return fmt.Errorf("failed to get client identity: %v", err)
	}
	
	// SECURITY CRITICAL: Verify client is authorized to write as agentID
	// Threat mitigated: T1078 (Valid Accounts) - Prevents agent spoofing
	isAuthorized, err := s.verifyAgentIdentity(ctx, clientID, agentID)
	if err != nil || !isAuthorized {
		return fmt.Errorf("unauthorized: client %s is not authorized for agent %s", clientID, agentID)
	}

	// -------------------------------------------------------------------------
	// 2. CRYPTO OP: HSM Signature Verification
	// -------------------------------------------------------------------------
	// Reconstruct payload string for signature verification
	payload := fmt.Sprintf("%s|%s|%s|%s|%s|%s|%d|%s",
		filePath, blake3Hash, sha256Hash, ipfsCID, dekKeyRef, agentID, timestampNano, attestationHash)

	// SECURITY CRITICAL: Verify the ECDSA-P384 signature generated by the agent's HSM
	// Threat mitigated: T1557 (Adversary-in-the-Middle) - Binds payload to hardware key
	validSig, err := s.verifyHSMSignature(ctx, agentID, payload, hsmSignature)
	if err != nil || !validSig {
		return fmt.Errorf("cryptographic verification failed: invalid HSM signature")
	}

	// -------------------------------------------------------------------------
	// 3. CRYPTO OP: Zero-Knowledge Proof (ZKP) Verification
	// -------------------------------------------------------------------------
	// Retrieve current compliance state (Merkle root of allowed hashes)
	currentRoot, err := s.getComplianceStateRoot(ctx)
	if err != nil {
		return fmt.Errorf("failed to retrieve compliance state root: %v", err)
	}

	// SECURITY CRITICAL: Verify ZKP (Groth16/PLONK) proof
	// Threat mitigated: Unauthorized file modification (T1565.001) passing validation
	isCompliant := s.VerifyCompliance(blake3Hash, currentRoot, zkpProof)
	
	status := "NON_COMPLIANT"
	if isCompliant {
		status = "COMPLIANT"
	}

	// -------------------------------------------------------------------------
	// 4. LEDGER COMMIT
	// -------------------------------------------------------------------------
	txID := ctx.GetStub().GetTxID()

	record := FileRecord{
		TxID:                txID,
		FilePath:            filePath,
		Blake3Hash:          blake3Hash,
		Sha256Hash:          sha256Hash,
		IpfsCID:             ipfsCID,
		DekKeyRef:           dekKeyRef,
		AgentID:             agentID,
		TimestampNano:       timestampNano,
		HSMSignature:        hsmSignature,
		AttestationHash:     attestationHash,
		ComplianceStateRoot: currentRoot,
		ComplianceStatus:    status,
	}

	recordJSON, err := json.Marshal(record)
	if err != nil {
		return err
	}

	// SECURITY CRITICAL: Check for duplicate CID to prevent replay attacks
	exists, err := s.cidExists(ctx, ipfsCID)
	if err != nil {
		return err
	}
	if exists {
		return fmt.Errorf("replay attack detected: CID %s already committed", ipfsCID)
	}

	// PutState commits the record to the ledger
	err = ctx.GetStub().PutState(txID, recordJSON)
	if err != nil {
		return fmt.Errorf("failed to put state: %v", err)
	}

	// -------------------------------------------------------------------------
	// 5. EVENT EMISSION
	// -------------------------------------------------------------------------
	// Emit indexed event for downstream consumption (AI Anomaly Detection / SIEM)
	// Threat mitigated: T1070 (Indicator Removal) - downstream consumers notified instantly
	err = ctx.GetStub().SetEvent("FileChangeRecorded", recordJSON)
	if err != nil {
		return fmt.Errorf("failed to set event: %v", err)
	}

	return nil
}

// FlagSuspiciousChange is invoked by the AI Anomaly Detection Middleware
// if it scores an event above the FP SLA threshold.
func (s *SmartContract) FlagSuspiciousChange(ctx contractapi.TransactionContextInterface, originalTxID string, anomalyScore float64, explanation string) error {
	// 1. Verify caller is the AI identity (omitted for brevity)
	
	// 2. Retrieve original record
	recordJSON, err := ctx.GetStub().GetState(originalTxID)
	if err != nil || recordJSON == nil {
		return fmt.Errorf("record not found: %s", originalTxID)
	}

	var record FileRecord
	err = json.Unmarshal(recordJSON, &record)
	if err != nil {
		return err
	}

	// 3. Update status
	record.ComplianceStatus = "UNDER_INVESTIGATION"
	updatedJSON, _ := json.Marshal(record)
	ctx.GetStub().PutState(originalTxID, updatedJSON)

	// 4. Save the flag
	flag := SuspiciousFlag{
		OriginalTxID: originalTxID,
		AnomalyScore: anomalyScore,
		Explanation:  explanation,
		Timestamp:    time.Now().Unix(),
	}
	flagJSON, _ := json.Marshal(flag)
	
	// Use a composite key for the flag so multiple flags can exist per tx
	flagKey, _ := ctx.GetStub().CreateCompositeKey("SuspiciousFlag", []string{originalTxID, fmt.Sprintf("%d", flag.Timestamp)})
	ctx.GetStub().PutState(flagKey, flagJSON)

	// 5. Emit alert event
	ctx.GetStub().SetEvent("SuspiciousChangeDetected", flagJSON)

	return nil
}

// VerifyCompliance acts as the ZKP verification stub
// Tradeoff context:
// - Groth16: Requires circuit-specific trusted setup (ceremony). O(1) verification (~10ms).
// - PLONK: Universal setup. Slightly larger proof size and slower verification (~30ms).
// For this high-throughput log pipeline, Groth16 is preferable to minimize endorsement latency.
func (s *SmartContract) VerifyCompliance(blake3Hash, merkleRoot, proof string) bool {
	// TODO: Integrate actual ZKP verifier library (e.g., gnark).
	// Pseudocode:
	// verifierKey := LoadVerifierKey("compliance_circuit_vk")
	// publicInputs := []fr.Element{blake3Hash, merkleRoot}
	// return gnark.Verify(proof, verifierKey, publicInputs)
	
	// Return true for compilation/stub purposes
	return true
}

// --- Helper Functions (Stubs for demonstration) ---

func (s *SmartContract) verifyAgentIdentity(ctx contractapi.TransactionContextInterface, clientID, agentID string) (bool, error) {
	// TODO: Map client MSP ID to registered agent ID in configuration state
	return true, nil
}

func (s *SmartContract) verifyHSMSignature(ctx contractapi.TransactionContextInterface, agentID, payload, signatureBase64 string) (bool, error) {
	// TODO: 
	// 1. Fetch agent's registered public key (ECDSA-P384) from ledger state
	// 2. Decode base64 signature
	// 3. Hash the payload with SHA-384
	// 4. Return ecdsa.Verify(pubKey, hash, r, s)
	return true, nil
}

func (s *SmartContract) getComplianceStateRoot(ctx contractapi.TransactionContextInterface) (string, error) {
	// TODO: Retrieve the latest Merkle root from the policy contract namespace
	return "0xCurrentMerkleRootStub", nil
}

func (s *SmartContract) cidExists(ctx contractapi.TransactionContextInterface, cid string) (bool, error) {
	// TODO: Query state by CID index
	return false, nil
}

func main() {
	chaincode, err := contractapi.NewChaincode(&SmartContract{})
	if err != nil {
		fmt.Printf("Error creating FileIntegrity chaincode: %s", err.Error())
		return
	}

	if err := chaincode.Start(); err != nil {
		fmt.Printf("Error starting FileIntegrity chaincode: %s", err.Error())
	}
}
